"""add image_url to games

Revision ID: 16317e3eb18a
Revises: b2316e804cdc
Create Date: 2026-03-21 21:57:00.882056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16317e3eb18a'
down_revision: Union[str, Sequence[str], None] = 'b2316e804cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'image_url')
    # ### end Alembic commands ###
