"""remove_paid_reviews_logic

Revision ID: 183e55366988
Revises: 591e9d6bdc3a
Create Date: 2026-03-24 18:33:01.380133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '183e55366988'
down_revision: Union[str, Sequence[str], None] = '591e9d6bdc3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'price')
    op.drop_column('reviews', 'is_paid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
