"""add aliases to games

Revision ID: 591e9d6bdc3a
Revises: 8d11d3c2752f
Create Date: 2026-03-23 16:52:32.464829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '591e9d6bdc3a'
down_revision: Union[str, Sequence[str], None] = '8d11d3c2752f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('aliases', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'aliases')
    # ### end Alembic commands ###
