"""add rating to games

Revision ID: 5b6219d3d9fc
Revises: 33937b3f5439
Create Date: 2026-03-14 13:16:10.826950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6219d3d9fc'
down_revision: Union[str, Sequence[str], None] = '33937b3f5439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'rating')
    # ### end Alembic commands ###
