"""add_premium_and_banner_to_user

Revision ID: 849f314229df
Revises: 183e55366988
Create Date: 2026-03-24 18:45:33.598122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '849f314229df'
down_revision: Union[str, Sequence[str], None] = '183e55366988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('premium_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('premium_theme', sa.String(), nullable=True))
    op.add_column('users', sa.Column('banner_url', sa.String(), nullable=True))
    op.alter_column('users', 'banned_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'banned_until',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('users', 'banner_url')
    op.drop_column('users', 'premium_theme')
    op.drop_column('users', 'premium_until')
    op.drop_column('users', 'is_premium')
    # ### end Alembic commands ###
