"""add ban fields to users

Revision ID: affab7791f17
Revises: b0d452dbd069
Create Date: 2026-03-21 11:55:53.836453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'affab7791f17'
down_revision: Union[str, Sequence[str], None] = 'b0d452dbd069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('banned_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banned_until')
    op.drop_column('users', 'is_banned')
    # ### end Alembic commands ###
